version: '{build}'
skip_tags: true
environment:
  matrix:
    - nodejs_version: '16.16.0'
  COVERALLS_REPO_TOKEN:
    secure: +2Ll2dKT0qrnuH+roy8Pn0lWqulLvVLBLUpsKevdZ0dFC1p6h0TZYTQ8OVYCb5Rl
  CHROMATIC_PROJECT_TOKEN:
    secure: zbf0sDEE5W+XKd1h+QvI2w==
init:
  - git config --global core.autocrlf input
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install --ignore-scripts
build: off
test_script:
  - node --version
  - yarn test
  - yarn build
on_success:
  - yarn publish:code-coverage
  - yarn publish:chromatic
cache:
  - node_modules -> package.json
  